# .circleci/config.yml

version: 2.1

defaults: &defaults
  macos:
    xcode: '12.0.0'
  working_directory: ~/aws-sdk-ios-spm

references:
  repo_cache_key: &repo_cache_key v2-repo-{{ .Branch }}-{{ .Revision }}

  restore_repo: &restore_repo
    restore_cache:
      keys:
        - *repo_cache_key
        - v2-repo-{{ .Branch }}
        - v2-repo

commands:
  make_artifacts_directory:
    steps:
      - run:
          name: Make artifacts directory
          command: mkdir -p "artifacts"
  
  upload_artifacts:
    steps:
      - store_artifacts:
          path: artifacts

jobs:
  checkout_code:
    <<: *defaults
    steps:
      - *restore_repo
      - checkout
      - save_cache:
          key: *repo_cache_key
          paths:
            - ~/aws-sdk-ios-spm

  release:
    <<: *defaults
    steps:
      - *restore_repo
      - run:
          name: Listing
          command: |
            ls
            ls ~/aws-sdk-ios-spm/*
      - run:
          name: Prepare git
          command: |
            git config --local user.name "${GITHUB_SPM_RELEASE_USER}"
            git fetch
            git remote -v
      - run:
          name: Extract version
          command: |
            release_version=$(cat Package.swift | grep -o -E '([0-9]+)\.([0-9]+)\.([0-9]+)')
            echo $release_version
      - run:
          name: Merge release branch to main branch
          command: |
            git fetch origin testMain
            echo "fetched"
            git checkout testcci
            echo "checkout"
            git rebase origin/testMain
            echo "rebase"
            git checkout testMain
            echo "checkout main"
            git merge testcci
            echo "merge"
            git push https://${GITHUB_SPM_TOKEN}@github.com/aws-amplify/aws-sdk-ios-spm.git
      - run:
          name: Update tag
          command: |
            echo $release_version
            git tag ${release_version}
            git push --tags -q https://${GITHUB_SPM_TOKEN}@github.com/aws-amplify/aws-sdk-ios-spm.git 
            
workflows:

  release_sdk:
    jobs:
      - checkout_code:
          filters:
            branches:
              only: 
                - testcci
      - release:
          requires:
              - checkout_code
          filters:
            branches:
              only: 
                - testcci
          

